### ISSUE TITLE
Вместо apply используйте оператор spread (...), чтобы преобразовать массив к списку аргументов

### ISSUE THREAD

**Issue by frontgirl** [Jolja06/js-game-netology#1]
https://github.com/Jolja06/js-game-netology/blob/47599d0ce954b9142a40bcedb33efc8145e74f6f/game.js#L113

**Comment by Jolja06** [comment]
Исправлено: https://github.com/Jolja06/js-game-netology/blob/211795e673029bb50f8010b227555b16f74a8b4a/game.js#L113
